#!/usr/bin/env bash

if [ `whoami` != 'azuracast' ]; then
    echo 'This script must be run as the "azuracast" user. Rerunning...'
    sudo -E -u azuracast azuracast_install $@
    exit 1
fi

update_mode=0
release_update=0
original_args=$*

while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do case $1 in
  --update )
    update_mode=1
    ;;

  -r | --release )
    release_update=1
    ;;
esac; shift; done
if [[ "$1" == '--' ]]; then shift; fi

if [ $update_mode = 1 ]; then
    echo "Updating AzuraCast..."
else
    echo "Installing AzuraCast..."
fi

APPLICATION_ENV="${APPLICATION_ENV:-production}"
echo "(Environment: $APPLICATION_ENV)"

if [ $APPLICATION_ENV = "production" ]; then
    if [ $release_update = 1 ]; then
        composer create-project azuracast/azuracast /var/azuracast/new ^0.9.3 --prefer-dist --no-install
    else
        composer create-project azuracast/azuracast /var/azuracast/new dev-master --prefer-source --keep-vcs --no-install
    fi
    
    rsync -a -v -q /var/azuracast/new/ /var/azuracast/www
    rm -rf /var/azuracast/new

    composer update --lock
    composer install --no-dev --prefer-dist
else
    if [ $APPLICATION_ENV = "testing" ]; then
        sudo mkdir -p vendor
        sudo chmod -R 0744 vendor
        sudo chown -R azuracast:azuracast vendor
    fi

    composer update --lock
    composer install
fi

azuracast_cli azuracast:setup ${original_args}